server:
  port: 8081
  context-path: /demo
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  aop:
    auto: true
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    data-username: root
    data-password: turing1984
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location:
  mapper-locations:




